### ISSUE TITLE
Notification failure , not registered received 

### ISSUE THREAD

**Issue by mshaileshr** [prabhat1707/Firebase-Push-Notification-Api-#4]

**Comment by prabhat1707** [comment]
please check your fcm server key

**Comment by mshaileshr** [comment]
Hey Prabhat, Could you pls help me in this error:
I am receiving fcm server key but getting below exception and fail response:

2019-04-07 14:37:45.059 3453-3485/com.visit.classesapp W/System.err: javax.net.ssl.SSLProtocolException: Read error: ssl=0x771b43fc80: Failure in SSL library, usually a protocol error
2019-04-07 14:37:45.059 3453-3485/com.visit.classesapp W/System.err: error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE (external/boringssl/src/ssl/ssl_lib.cc:717 0x7718ff589f:0x00000000)
2019-04-07 14:37:45.059 3453-3485/com.visit.classesapp W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
2019-04-07 14:37:45.059 3453-3485/com.visit.classesapp W/System.err:     at com.android.org.conscrypt.SslWrapper.read(SslWrapper.java:384)
2019-04-07 14:37:45.059 3453-3485/com.visit.classesapp W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:541)
2019-04-07 14:37:45.059 3453-3485/com.visit.classesapp W/System.err:     at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
2019-04-07 14:37:45.059 3453-3485/com.visit.classesapp W/System.err:     at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
2019-04-07 14:37:45.059 3453-3485/com.visit.classesapp W/System.err:     at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
2019-04-07 14:37:45.060 3453-3485/com.visit.classesapp W/System.err:     at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
2019-04-07 14:37:45.060 3453-3485/com.visit.classesapp W/System.err:     at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
2019-04-07 14:37:45.060 3453-3485/com.visit.classesapp W/System.err:     at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
2019-04-07 14:37:45.060 3453-3485/com.visit.classesapp W/System.err:     at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
2019-04-07 14:37:45.060 3453-3485/com.visit.classesapp W/System.err:     at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
2019-04-07 14:37:45.060 3453-3485/com.visit.classesapp W/System.err:     at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
2019-04-07 14:37:45.060 3453-3485/com.visit.classesapp W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
2019-04-07 14:37:45.060 3453-3485/com.visit.classesapp W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
2019-04-07 14:37:45.060 3453-3485/com.visit.classesapp W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244)
2019-04-07 14:37:45.060 3453-3485/com.visit.classesapp W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
2019-04-07 14:37:45.060 3453-3485/com.visit.classesapp W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(Unknown Source:0)
2019-04-07 14:37:45.060 3453-3485/com.visit.classesapp W/System.err:     at com.trenzlr.firebasenotificationhelper.NetworkCall.doInBackground(NetworkCall.java:57)
2019-04-07 14:37:45.060 3453-3485/com.visit.classesapp W/System.err:     at com.trenzlr.firebasenotificationhelper.NetworkCall.doInBackground(NetworkCall.java:30)
2019-04-07 14:37:45.060 3453-3485/com.visit.classesapp W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
2019-04-07 14:37:45.060 3453-3485/com.visit.classesapp W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-04-07 14:37:45.061 3453-3485/com.visit.classesapp W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
2019-04-07 14:37:45.061 3453-3485/com.visit.classesapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2019-04-07 14:37:45.061 3453-3485/com.visit.classesapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2019-04-07 14:37:45.061 3453-3485/com.visit.classesapp W/System.err:     at java.lang.Thread.run(Thread.java:764)

**Comment by prabhat1707** [comment]
did u use any networking library after it?

**Comment by mshaileshr** [comment]
NO, There is not network call
